<?php


namespace App\Providers;


use App\Models\ProductsBundle;
use App\Repositories\EloquentImpl\Item\ItemRepository;
use App\Repositories\EloquentImpl\Offer\OfferRepository;
use App\Repositories\EloquentImpl\Product\ProductRepository;
use App\Repositories\EloquentImpl\ProuductsBundle\ProductsBundleRepsitory;
use App\Repositories\Interfaces\ICartRepository;
use App\Repositories\Interfaces\IItemRepository;
use App\Repositories\Interfaces\IOfferRepository;
use App\Repositories\Interfaces\IProductsBundleRepository;
use App\Repositories\IRepository;
use App\Services\Interfaces\IProductService;
use Closure;
use Illuminate\Support\ServiceProvider;

class RepositoryServiceProvider extends ServiceProvider
{
    // we could map here any repository that not direct associate with service
    private $map = [
        IProductsBundleRepository::class => ProductsBundleRepsitory::class
    ];
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }
    public function boot()
    {
        foreach ($this->map as $abstract => $class) {
            $this->app->bind($abstract, $class);
        }
    }

}
